
name: Weekly Update Lagu Nias

on:
  schedule:
    - cron: '0 22 * * 6'  # Setiap minggu (Minggu pagi WIB)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python scripts/fetch_youtube_data.py

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/*
        git commit -m "Update top lagu Nias"
        git push
